### ISSUE TITLE
Second attempt also failed. Error is not due to MFA code reuse.

### ISSUE THREAD

**Issue by tekumara** [glassechidna/awsweb#23]
```
$ ae lab
Assume Role MFA token code: 123456
Second attempt also failed. Error is not due to MFA code reuse.
```

**Comment by tekumara** [comment]
This can happen when your AWS access key has expired. Create a new AWS access key from the console and update _~/.aws/credentials_ to use it.

**Comment by cowboy-bebug** [comment]
In my case, `~/.aws/credentials` wasn't set up correctly.
It only had credentials for the `default` profile -> meaning the next time I run, `aws cli` tries to use the expired default credentials.
